//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public class FogManager
{
	GameObject[][] fogs;
	
	private static FogManager Instance;
	
	public static FogManager getInstance()
	{
		if(Instance == null)
		{
			Instance = new FogManager();
		}
		return Instance;
	}
	
	private FogManager()
	{
		fogs = new GameObject[MapGenerator.width][];
		for(int i=0;i<20;i++)
		{
			fogs[i] = new GameObject[MapGenerator.height];
			for (int j = 0; j < 20; j++)
			{
				fogs[i][j] = null;
			}
		}
	}
	
	public void addFog(int x, int y, GameObject fog)
	{
		fogs[x][y] = fog;
	}
}

